### ISSUE TITLE
Consider having the entire crates.io index/db automatically imported as bb packages

### ISSUE THREAD

**Issue by jmesmon** [meta-rust/meta-rust#12]
This would also include adding a crates.io fetcher to get the source code for a crate.

**Comment by posborne** [comment]
What are your ideas on how this would be implemented?  Code generation that generates actual bb recipe files for each crate or something that doesn't require text files to be written out?

**Comment by jmesmon** [comment]
Ideally we wouldn't have the actual text files, but instead add the idea of a recipe into bitbake using the crates.io index git repo as the source for data. Unclear if that is possible, though (I haven't dug into the python hooks in bitbake extensively enough yet).

Which is why I'd see auto-generation of the text files as a first step. At the point where we do have auto-generation though, it would probably make sense to have a separate layer which was automatically updated from crates.io's changes rather than pouring a bunch of automatic changes into `meta-rust`.
