### ISSUE TITLE
how to handle krogoth branch

### ISSUE THREAD

**Issue by cardoe** [meta-rust/meta-rust#122]
So I'm using krogoth and I actually need Rust 1.12.1 for my project. Unfortunately a lot of work has gone into master that makes it incompatible to just cherry-pick that version into krogoth (in fact its not possible because until recently multiple versions couldn't be available at all). There's also issue #87 which is fixed in master.

So the question is do we want to replace the krogoth branch with one based on master (effectively a merge and then reverting out the changes we've done for explicitly for morty) or should we make a `krogoth-1.12.1` branch that will address #87 and my issues. I would only support the `krogoth-1.12.1` branch and consider the older one as deprecated.

/cc @meta-rust/maintainers feedback?

**Comment by jmesmon** [comment]
I'm fine either way (at the moment I'm tracking newer releases of yocto rather closely), but here are some thoughts:

Seems like upside of just using the `krogoth` branch would be folks would be less likely to use something that is a bit unmaintained.

I know the gen-ivi folks are also trying to use krogoth, so it might make sense to see how this would affect them (the question you asked here https://github.com/meta-rust/meta-rust/issues/87#issuecomment-264240711 seems key). A backport of more recent changes to krogoth would also break cargo.bbclass users currently on krogoth, so it could be useful to find out how straight forward updating the old cargo recipes would be.

An alternate on the last point would be to bring back the old-cargo mechanism & name the new cargo bbclass something else (or somehow infer the desired method), though having krogoth & master/morty recipes be similar would be nice.

I expect the cargo.bbclass changes could be more breaking than a rust version update.
