### ISSUE TITLE
Native build assumes corei7 processor extensions

### ISSUE THREAD

**Issue by derekstraka** [meta-rust/meta-rust#139]
## Version(s) of meta-rust
Morty (others affected as well)

## Version(s) of poky and/or oe-core
Morty and morty

## Expected result
rust-native should build correctly

## Actual result
rust-native build fails with Illegal instruction

## Steps to reproduce
Attempt to build rust-native on a machine that does not have 'modern' features of a core i7.

The optimizations for rust will not execute on older intel processors because we specify a tune feature set of corei7.  This is not always the case.

CPU Info
```
processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 15
model name	: Intel(R) Xeon(R) CPU            5160  @ 3.00GHz
stepping	: 6
microcode	: 0xd2
cpu MHz		: 3000.200
cache size	: 4096 KB
physical id	: 3
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca lahf_lm tpr_shadow dtherm
bugs		:
bogomips	: 6000.09
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
```

**Comment by cardoe** [comment]
Fixed by #140.
