### ISSUE TITLE
use bitbake installed jemalloc

### ISSUE THREAD

**Issue by jmesmon** [meta-rust/meta-rust#17]
ie: if there is a bitbake package for jemalloc, we should allow usage of it rather than building our own.

**Comment by cardoe** [comment]
I haven't been able to do this on Gentoo due to the patching that happens to jemalloc in the Rust build process. It alters the API and ABI of jemalloc.

**Comment by cardoe** [comment]
I looked again at this when bumping Rust in Gentoo and there are further changes from stock jemalloc's API and ABI which IMHO render the two as significantly different enough to not make this worth it. @jmesmon Your thoughts?

**Comment by jmesmon** [comment]
This ticket was primarily a reminder to take a look at using non-integrated jemalloc at some point.

As it sounds like (from your investigation) that that isn't (easily) possible, it should be fine to close this.

**Comment by cardoe** [comment]
Alright. I'll periodically look at this and should the deltas close a little bit we can re-open.

**Comment by cardoe** [comment]
They're breaking jemalloc out into its own crate, so this should resolve itself.

https://github.com/rust-lang/rust/issues/36963
https://crates.io/crates/jemallocator
