### ISSUE TITLE
Create rocko branch

### ISSUE THREAD

**Issue by hmvp** [meta-rust/meta-rust#186]
## Version(s) of meta-rust
rocko
## Version(s) of poky and/or oe-core
rocko
## Expected result
I expect to be able to build rocko based images using the rocko branch for all meta layers
## Actual result
I have to make an exception and use the master branch?
## Steps to reproduce
-

**Comment by hmvp** [comment]
One actual issue with using master for a Rocko release is that a lot of getVar calls are missing their expand argument. It seems they were remove before pyro because they were thought to default to True. However in Rocko it is a hard error to miss that argument and in Pyro the default is still False...

**Comment by derekstraka** [comment]
I created a preliminary rocko branch based on what is in master.

**Comment by hmvp** [comment]
Everything seems to work so far.

**Comment by derekstraka** [comment]
Completed.
