### ISSUE TITLE
thud branch

### ISSUE THREAD

**Issue by floion** [meta-rust/meta-rust#218]
Hi,
is thud support close to be released? I just checked and did not see a `thud` branch created.

Thank you

**Comment by floion** [comment]
cc @derekstraka

**Comment by derekstraka** [comment]
I'm going to be honest, and say that I have not been actively testing with thud pre-releases.  If you or someone you know has verified meta-rust/master works, I'll make the branch

**Comment by siredmar** [comment]
As thud has been released, will there be any effort for a thud branch?

**Comment by srwalter** [comment]
FWIW, I'm using the master branch with sumo, so I would expect that the master branch works with thud as well

**Comment by floion** [comment]
Hi, so can the `thud` and `warrior` branches be created?

**Comment by wdehoog** [comment]
Just to let you know. I am currently using master to build my layer with the thud branches of poky and meta-openembedded.

**Comment by floion** [comment]
Thanks, so we'll just use master until these branches are officially created

**Comment by floion** [comment]
Hi @derekstraka now what about dunfell? :)

**Comment by aj-bagwell** [comment]
The new override syntax (bf6705fb7f41b16c3277cbf84af0b9757dcd3a01) breaks rust on the old release, would it be possible to create branches for them?

**Comment by srwalter** [comment]
Which release are you interested in?

**Comment by aj-bagwell** [comment]
`hardknott` and `dunfell` (LTS) at a minimum as they are the two releases supported. But I would not mind `zeus` and `gatesgarth` too.

**Comment by srwalter** [comment]
Created hardknott, zeus, and gatesgarth branches
