### ISSUE TITLE
0001-Support-progress-on-other-than-tty-s.patch missing from dd0fc89389d3 ("cargo: fix progress output")

### ISSUE THREAD

**Issue by akiernan** [meta-rust/meta-rust#274]
## Version(s) of meta-rust
dd0fc89389d3 ("cargo: fix progress output")
## Version(s) of poky and/or oe-core
master
## Expected result
Builds
## Actual result
Fails due to missing 0001-Support-progress-on-other-than-tty-s.patch
## Steps to reproduce
Pull latest `meta-rust` into OE-core build, run `bitbake cargo-native`, build will fail:

`00:08:58.447  ERROR: cargo-native-1.41.0-r0 do_fetch: Fetcher failure: Unable to find file file://0001-Support-progress-on-other-than-tty-s.patch;striplevel=4 anywhere. The paths that were searched were:`

**Comment by srwalter** [comment]
Fixed!
