### ISSUE TITLE
Zeus Branch use new syntax but shouldn't

### ISSUE THREAD

**Issue by clementperon** [meta-rust/meta-rust#368]
The meta-rust zeus branch have this commit:
https://github.com/meta-rust/meta-rust/commit/bf6705fb7f41b16c3277cbf84af0b9757dcd3a01

But this new syntax is not available under zeus @shr-project

**Comment by shr-project** [comment]
I don't know why it was backported to zeus, I've created PR only for master as it's only for dunfell and newer.

Did the zeus branch exist before? maybe it was just branched from wrong commit, it should be parent of this change. Now it should be reverted from zeus branch.
