### ISSUE TITLE
CI is broken, no self-hosted runner available to pick up the job

### ISSUE THREAD

**Issue by ColinFinck** [meta-rust/meta-rust#401]
CI is currently failing all the time due to no self-hosted runner available to pick up the job: https://github.com/meta-rust/meta-rust/actions/runs/3713453290/jobs/6327925120

I don't know who set it up, who is supposed to run the self-hosted runner, and whether there is any alternative. Which is why I can only open this issue.
Pinging the last editors of the GitHub workflow file though:
- @srwalter 
- @kazuki0824 
- @shr-project 
- @weltling

**Comment by srwalter** [comment]
I host the runner.  Not sure why the VM wasn't running, but it's fixed now
