### ISSUE TITLE
Yocto versioned branches

### ISSUE THREAD

**Issue by cardoe** [meta-rust/meta-rust#54]
So meta-rust always had the development happening on a master branch but for work I need to be able to ship things based on Yocto release branches (e.g. fido, jethro, kergoth) so I'd like to push those branches into this repo now. Previously they've been here:

https://github.com/starlab-io/meta-rust/tree/fido
https://github.com/starlab-io/meta-rust/tree/jethro

They diverged from meta-rust a little bit but now that we're all working together on this project I see future named branches just forking from master. Sound ok to everyone? @jmesmon @derekstraka @srwalter

**Comment by srwalter** [comment]
That sounds reasonable to me

**Comment by derekstraka** [comment]
Works for me

**Comment by cardoe** [comment]
Pushed.
