### ISSUE TITLE
Add krogoth branch

### ISSUE THREAD

**Issue by hmvp** [meta-rust/meta-rust#59]
Yocto 2.1 is the current stable release. It would be nice if meta-rust had a krogoth branch to support 2.1

**Comment by cardoe** [comment]
We're currently working on krogoth in master right now. Once krogoth support is working well, we'll make a branch.

cc @derekstraka

**Comment by derekstraka** [comment]
@cardoe - Should we create a krogoth branch or did you want to wait for an updated rust version?

**Comment by derekstraka** [comment]
@cardoe - I validated the master build.  The only issue I ran into was the random number blocking.  We will probably want to pull that patch over while we use rust 1.7

**Comment by cardoe** [comment]
I think we just make a krogoth branch now but I agree let's backport the rng fix

**Comment by cardoe** [comment]
krogoth branch has been pushed
