### ISSUE TITLE
Update libgit2 and push into meta-openembedded

### ISSUE THREAD

**Issue by derekstraka** [meta-rust/meta-rust#62]
The libgit2 recipes can be updated to the latest version and pushed into meta-openembedded.  They can then be removed from meta-rust.  There are a few other consumers of the library that would benefit from it being in meta-openembedded instead of maintained in this layer.

**Comment by derekstraka** [comment]
It looks like the meta-rust common license can also be removed when the libgit2 recipes are moved

**Comment by derekstraka** [comment]
Patch submitted to the [meta-openembedded ML](http://lists.openembedded.org/pipermail/openembedded-devel/2016-August/108422.html)

**Comment by cardoe** [comment]
Looks like v2 is [posted here](http://lists.openembedded.org/pipermail/openembedded-devel/2016-August/108445.html).

**Comment by derekstraka** [comment]
This has been merged into meta-openembedded master, so I'll create a PR once krogoth gets created in #59

**Comment by cardoe** [comment]
krogoth has been created

**Comment by cardoe** [comment]
Closed via #75
