### ISSUE TITLE
Continuous Integration Testing

### ISSUE THREAD

**Issue by cardoe** [meta-rust/meta-rust#94]
We need to get some form of CI for this project. In the past I tried to use Travis CI but bumped up against the 1 hour time limit every time.

**Comment by derekstraka** [comment]
I've setup a jenkins server we can use - ci.asterius.io with a couple of slaves that can be used for CI.

**Comment by cardoe** [comment]
@jmesmon Can you add the `metarustbot` user to the project and give it `repo` access?

**Comment by jmesmon** [comment]
repo or organization?

I've sent invites for both. Note that the way things are configured right now, all organization members can create repositories, add new collaborators to existing repositories, and have read & write access to organization repositories (or at least, I believe that's what should happen based on what github's settings are telling me). It might make sense to use teams to limit this somewhat.

**Comment by cardoe** [comment]
Well the `repo` access I needed was actually the API token permission so that was my confusion. But org or repo works. If we add other repos to this org (not sure if we will) then we can give it more access.
